# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:2.7

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements-dev.txt

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  artifacts:
    paths: [gl-code-quality-report.json]


stages:
  - build
  - test

Build:
    stage: build
    script:
        - pytest --cov-report term-missing:skip-covered --cov=.
    artifacts:
        paths:
        - htmlcov/index.html

Test:
    stage: test
    script:
        - pytest --cov-report term-missing:skip-covered --cov=.
    artifacts:
        paths:
        - htmlcov/index.html
