# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-11-17 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_auth', '0022_tungauser_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tungauser',
            name='sso_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
