# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-08 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_utils', '0025_auto_20181116_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviterequest',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
