# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-15 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_projects', '0027_interestpoll_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='update_days',
            field=models.CharField(default='Monday,Tuesday,Wednesday,Thursday,Friday', max_length=40),
        ),
    ]
