# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-05 12:03
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_projects', '0028_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='progressevent',
            name='type',
            field=models.CharField(choices=[(b'developer', b'Developer Update'), (b'developer_rating', b'Developer Rating'), (b'pm', b'PM Report'), (b'client', b'Client Survey'), (b'milestone', b'Milestone'), (b'internal', b'Internal Milestone')], default=b'developer', help_text='developer - Developer Update,developer_rating - Developer Rating,pm - PM Report,client - Client Survey,milestone - Milestone,internal - Internal Milestone', max_length=50),
        ),
        migrations.AddField(
            model_name='developerrating',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunga_projects.ProgressEvent'),
        ),
        migrations.AddField(
            model_name='developerrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
