# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-29 15:42
from __future__ import unicode_literals

from django.db import migrations, models


projects = []

def get_old_projects_and_their_types(apps, schema_editor):
    Project = apps.get_model('tunga_projects', 'Project')
    ProjectType = apps.get_model('tunga_projects', 'ProjectType')

    for project in Project.objects.all():
        projects.append({'id': project.pk, 'type': project.type})

def migrate_old_projects_to_new_project_types(apps, schema_editor):
    Project = apps.get_model('tunga_projects', 'Project')
    ProjectType = apps.get_model('tunga_projects', 'ProjectType')

    for p in projects:
        project = Project.objects.get(pk=p['id'])
        project_type = ProjectType.objects.get(name=p['type'].capitalize())
        project.type.add(project_type)


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_projects', '0030_create_default_project_types'),
    ]

    operations = [
        migrations.RunPython(get_old_projects_and_their_types),
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ManyToManyField(blank=True, to='tunga_projects.ProjectType'),
        ),
        migrations.RunPython(migrate_old_projects_to_new_project_types),
    ]
