# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-30 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_projects', '0031_developerrating_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='rate_deliverables_improvements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='status',
            field=models.CharField(blank=True, choices=[(b'on_schedule', b'On schedule'), (b'behind', b'Behind'), (b'stuck', b'Stuck'), (b'behind_progressing', b'Behind but Progressing'), (b'behind_stuck', b'Behind and Stuck'), (b'ahead', b'Ahead')], help_text='on_schedule - On schedule,behind - Behind,stuck - Stuck,behind_progressing - Behind but Progressing,behind_stuck - Behind and Stuck,ahead - Ahead', max_length=50, null=True),
        ),
    ]
