# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-11 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_projects', '0032_auto_20200130_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='reason_for_rating',
            field=models.TextField(blank=True, null=True),
        ),
    ]
