# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-11 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_projects', '0033_progressreport_reason_for_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerrating',
            name='reason_of_rating',
            field=models.TextField(blank=True, null=True),
        ),
    ]
