# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-01-20 12:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tunga_projects', '0035_auto_20201221_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_events_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
