# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-05 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0042_whitepaperuser_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='project_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='repository_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
