# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-10 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0043_auto_20200205_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerinvitation',
            name='category',
            field=models.CharField(blank=True, choices=[(b'developer', 'Developer'), (b'designer', 'Designer')], max_length=20, null=True),
        ),
    ]
