# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-01-27 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_profiles', '0045_profileproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
